Repository ursais/docker, pull requests merged in 2020-12, with the labels that each got.

#1 [IMP] Documentation
  .gitignore
  README.md
  odoo/12.0/Dockerfile
  odoo/12.0/entrypoint.sh
  odoo/12.0/odoo.conf
  odoo/12.0/wait-for-psql.py
  odoo/13.0/Dockerfile
  odoo/13.0/entrypoint.sh
  odoo/13.0/odoo.conf
  odoo/13.0/wait-for-psql.py
  odoo/14.0/Dockerfile
  odoo/14.0/entrypoint.sh
  odoo/14.0/odoo.conf
  odoo/14.0/wait-for-psql.py
  requirements.txt
Labels: documentation, enhancement

#2 [FIX] Odoo: security issues
  odoo/12.0/Dockerfile
  odoo/12.0/requirements.txt
  odoo/13.0/Dockerfile
  odoo/13.0/requirements.txt
  odoo/14.0/Dockerfile
  odoo/14.0/requirements.txt
Labels: bug

#3 [ADD] postgresql/13
  README.md
  postgresql/13.0/Dockerfile
Labels: enhancement

#4 [IMP] Documentation
  README.md
Labels: documentation, enhancement

#5 [IMP] Allow to extend and install packages and libraries
  odoo/12.0/Dockerfile
  odoo/13.0/Dockerfile
  odoo/14.0/Dockerfile
Labels: enhancement

#6 [FIX] odoo-13.0/entrypoint.sh: --test-enable not loading demo data
  odoo/13.0/entrypoint.sh
Labels: bug

#8 [FIX] odoo/*/entrypoint.sh
  odoo/12.0/entrypoint.sh
  odoo/13.0/entrypoint.sh
  odoo/14.0/entrypoint.sh
Labels: bug

#10 [fix][12.0] entrypoint: enable demo data in config
  odoo/12.0/entrypoint.sh
Labels: bug
